image: Visual Studio 2017

install:
  - git clone --branch php-sdk-2.2.0 https://github.com/Microsoft/php-sdk-binary-tools C:\build
  - curl -fsS -o php-devel-pack-7.3.11-nts-Win32-VC15-x64.zip https://windows.php.net/downloads/releases/php-devel-pack-7.3.11-nts-Win32-VC15-x64.zip
  - 7z x php-devel-pack-7.3.11-nts-Win32-VC15-x64.zip

build_script:
  - cd extension\php7
  - cmd /c C:\build\phpsdk-vc15-x64.bat -t C:\projects\php-meminfo\appveyor\build.bat
  - dir
